# insert your token below
token: your token here

# change the time before the user gets kicked (in seconds)
time_kick: 30

# message that is sent to the user that joins
joins_text: Welcome {}, if you're not a bot, tap the button below, 
            otherwise you will be kicked in 30 seconds.

# text in the button attached to the first message
button: I'M NOT A BOT

# the first message will be changed with this
notbot_text: Ok {}, you're not a bot.

# text prompted if they press the button
# and they aren't the one who joined the group
not4u_text: This button is not for you.